### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by jonahbrandwagt** [matthew1232/stockx-api#12]
Getting this error:

Unexpected token < in JSON at position 0

**Comment by ianrockefeller** [comment]
Also receiving this error, here is the output from the server:

`Error: 403 - "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"utf-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n    <title>Access to this page has been denied.</title>\n    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300\" rel=\"stylesheet\">\n    <style>\n        html, body {\n            margin: 0;\n            padding: 0;\n            font-family: 'Open Sans', sans-serif;\n            color: #000;\n        }\n\n        a {\n            color: #c5c5c5;\n            text-decoration: none;\n        }\n\n        .container {\n            align-items: center;\n            display: flex;\n            flex: 1;\n            justify-content: space-between;\n            flex-direction: column;\n            height: 100%;\n        }\n\n        .container > div {\n            width: 100%;\n            display: flex;\n            justify-content: center;\n        }\n\n        .container > div > div {\n            display: flex;\n            width: 80%;\n        }\n\n        .customer-logo-wrapper {\n            padding-top: 2rem;\n            flex-grow: 0;\n            background-color: #fff;\n            visibility: visible;\n        }\n\n        .customer-logo {\n            border-bottom: 1px solid #000;\n        }\n\n        .customer-logo > img {\n            padding-bottom: 1rem;\n            max-height: 50px;\n            max-width: 100%;\n        }\n\n        .page-title-wrapper {\n            flex-grow: 2;\n        }\n\n        .page-title {\n            flex-direction: column-reverse;\n        }\n\n        .content-wrapper {\n            flex-grow: 5;\n        }\n\n        .content {\n            flex-direction: column;\n        }\n\n        .page-footer-wrapper {\n            align-items: center;\n            flex-grow: 0.2;\n            background-color: #000;\n            color: #c5c5c5;\n            font-size: 70%;\n        }\n\n        @media (min-width: 768px) {\n            html, body {\n                height: 100%;\n            }\n        }\n    </style>\n    <!-- Custom CSS -->\n    \n</head>\n\n<body>\n<section class=\"container\">\n    <div class=\"customer-logo-wrapper\">\n        <div class=\"customer-logo\">\n            <img src=\"https://stockx-assets.imgix.net/logo/stockx-homepage-logo.png\" alt=\"Logo\"/>\n        </div>\n    </div>\n    <div class=\"page-title-wrapper\">\n        <div class=\"page-title\">\n            <h1>Please verify you are a human</h1>\n        </div>\n    </div>\n    <div class=\"content-wrapper\">\n        <div class=\"content\">\n\n            <div id=\"px-captcha\">\n            </div>\n            <p>\n                Access to this page has been denied because we believe you are using automation tools to browse the\n                website.\n            </p>\n            <p>\n                This may happen as a result of the following:\n            </p>\n            <ul>\n                <li>\n                    Javascript is disabled or blocked by an extension (ad blockers for example)\n                </li>\n                <li>\n                    Your browser does not support cookies\n                </li>\n            </ul>\n            <p>\n                Please make sure that Javascript and cookies are enabled on your browser and that you are not blocking\n                them from loading.\n            </p>\n            <p>\n                Reference ID: #4c3bdfa0-a5d9-11ea-b4bd-6991b77d26c4\n            </p>\n        </div>\n    </div>\n    <div class=\"page-footer-wrapper\">\n        <div class=\"page-footer\">\n            <p>\n                Powered by\n                <a href=\"https://www.perimeterx.com/whywasiblocked\">PerimeterX</a>\n                , Inc.\n            </p>\n        </div>\n    </div>\n</section>\n<!-- Px -->\n<script>\n    window._pxAppId = 'PX16uD0kOF';\n    window._pxJsClientSrc = '/16uD0kOF/init.js';\n    window._pxFirstPartyEnabled = true;\n    window._pxVid = '';\n    window._pxUuid = '4c3bdfa0-a5d9-11ea-b4bd-6991b77d26c4';\n    window._pxHostUrl = '/16uD0kOF/xhr';\n</script>\n<script>\n    var s = document.createElement('script');\n    s.src = '/16uD0kOF/captcha/captcha.js?a=c&u=4c3bdfa0-a5d9-11ea-b4bd-6991b77d26c4&v=&m=0';\n    var p = document.getElementsByTagName('head')[0];\n    p.insertBefore(s, null);\n    if (true) {\n        s.onerror = function () {\n            s = document.createElement('script');\n            var suffixIndex = '/16uD0kOF/captcha/captcha.js?a=c&u=4c3bdfa0-a5d9-11ea-b4bd-6991b77d26c4&v=&m=0'.indexOf('captcha.js');\n            var temperedBlockScript = '/16uD0kOF/captcha/captcha.js?a=c&u=4c3bdfa0-a5d9-11ea-b4bd-6991b77d26c4&v=&m=0'.substring(suffixIndex);\n            s.src = '//captcha.px-cdn.net/PX16uD0kOF/' + temperedBlockScript;\n            p.parentNode.insertBefore(s, p);\n        };\n    }\n</script>\n<!-- Custom Script -->\n\n</body>\n</html>\n"`

**Comment by alexchiriac** [comment]
Getting the same problem myself... Anybody have any clue on how to fix this?

**Comment by alexchiriac** [comment]
For anybody else looking for a fix, I've managed to solve this on my side by using a custom user-agent inside the library.

To avoid this sort of issue in the future, I would try to expose the user-agent to the API instantiation (something like a constructor argument) so that there's no user agent hardcoded at the library level.

The steps I did are as follows:
1. Clone this library yourself
2. Google how to find your browsers user agent
3. Inside the functions, (such as src/fetchproductdetails.js) replace the 'user-agent' with your own user agent
4. Open a terminal window inside the root folder of the library and run `npm link`
5. In your own project, run `npm link stockx-api` - this will make sure that the scripts you wrote make use of the version of the library which you've just modified

And that's it!

**Comment by matthew1232** [comment]
Glad you were able to find a solution @alexchiriac , thank you for sharing! Just pushed v1.0.5 of stockx-api, with the option to change your user agent for all requests in the constructor. To update run `yarn upgrade stockx-api` or `npm update stockx-api`. At the moment it looks like the README on npm hasn't updated so here's an example

```js
const stockxAPI = require('stockx-api');
const stockX = new stockxAPI({
    userAgent: 'youruseragenthere'
});
```

**Comment by ianrockefeller** [comment]
Nice work, guys!

**Comment by matthew1232** [comment]
For anyone who is still having this issue:
I just updated to 1.0.7 with http2 support to `searchProducts` and `fetchProductDetails`, along with a `newSearchProducts` method that doesn't have to pass PerimeterX to my knowledge. All tests passed on my computer with the updates. Please let me know if 1.0.7 solves the problem 🤞
